version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: gradle clean build
      - codecov/upload:
          file: build/reports/jacoco/test/jacocoTestReport.xml
      - run:
          name: Publish to Artifactoy
          command: curl --fail -T build/libs/owl-rules-1.1.${CIRCLE_BUILD_NUM}.jar -u$BINTRAY_USER:$BINTRAY_API_KEY https://api.bintray.com/content/johnowl/maven/owl-rules/1.1.${CIRCLE_BUILD_NUM}/com/johnowl/owl-rules-1.1.${CIRCLE_BUILD_NUM}.jar